# 에러 처리

- 에러가 발생하지 않는 코드를 작성하는 것은 불가능하다. 따라서 언제나 예외적인 상황이 발생할 수 있다는 것을 전제하고, 이에 대응하는 코드를 작성하는 것이 중요하다.

- JS 환경에서 에러 처리를 두 가지 방식으로 구현할 수 있다.

  1. JS에서 기본적으로 제공하는 메서드중 의도된 인수가 주어지지 않는 경우 null 또는 -1 값을 반환하는 메서드가 있다. 또한 객체의 의도치 않은 접근을 방지하기 위해 [옵셔널 체이닝(optional chaining operator)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining)을 사용함으로써 예외적인 상황에 반환되는 값으로 에러 상황을 식별하고 처리한다.

  - 이 방식은 예외 상황에 대한 결과로 에러를 발생시키는 것이 아닌, 실패값을 반환하며 처리하므로 "에러 처리" 보단 **방어적 프로그래밍(defensive programming)** 기법에 가까운 방식이다.

  2. try-catch-finally 문을 통해 에러 처리 코드를 미리 등록해 두고 에러가 발생하면 에러 코드로 점프(jump)하도록 한다.

  - 이 방식을 **에러 처리(error handling)** 라고 한다.

## 에러 객체

- JS 환경에서는 상황에 따라 표현할 수 있는 다양한 객체를 제공한다

- 일반적으로 사용자 정의(user-defined) 에러를 발생시킬 때 에러 객체의 인스턴스를 생성하고 throw 키워드를 사용해 에러를 발생 시킨다.

```js
// 각 에러 객체는 Error 객체를 상속한다.
console.log(Object.getPrototypeOf(TypeError.prototype) === Error.prototype);
console.log(
	Object.getPrototypeOf(ReferenceError.prototype) === Error.prototype
);
console.log(Object.getPrototypeOf(SyntaxError.prototype) === Error.prototype);
console.log(Object.getPrototypeOf(EvalError.prototype) === Error.prototype);
console.log(
	Object.getPrototypeOf(AggregateError.prototype) === Error.prototype
);
console.log(Object.getPrototypeOf(RangeError.prototype) === Error.prototype);
console.log(Object.getPrototypeOf(DOMException.prototype) === Error.prototype);

// 예외적으로 MediaError 객체는 Error 객체와 상속 관계를 가지지 않는다.
console.log(Object.getPrototypeOf(MediaError) === Function.prototype);
console.log(MediaError.constructor === Function);

// Error 객체는 Function 빌트인 객체의 인스턴스다.
console.log(Object.getPrototypeOf(Error) === Function.prototype);
console.log(Error.constructor === Function);
```

## throw - catch

- JS에서 일반적으로 throw - catch 문을 통해 에러를 처리하는 방식을 선호한다

- 에러는 throw 키워드를 통해 발생시킬 수 있다. throw 문에는 Error 객체가 아닌 다른 값도 입력할 수 있지만, 일반적인 방법이 아니다.

```js
const repeat = (cb, count) => {
	// 입력받은 인수의 타입이 의도한 타입이 아닌 경우 에러를 발생시킬 수 있다.

	// 일반적으로 에러 객체 생성자 함수에 입력되는 값은 에러 메시지 값으로, 에러 객체의 'message' 프로퍼티를 통해 참조할 수 있다.
	if (typeof count !== 'number')
		throw new TypeError('count must be a number!!');

	if (typeof cb !== 'function') throw new TypeError('cb must be a function!!');

	for (let i = 0; i < count; i++) {
		try {
			cb();
		} catch (e) {
			// 에러 추적성을 높히기 위해 상황에 따라 에러를 중첩해서 발생시킬 수 있다.

			// 생성자 함수의 두 번째 인수의 'cause' 옵션을 통해 상위 호출자에서 발생한 에러 정보를 포함하여 하위 호출자로 전파한다.

			// cause 옵션은 ES2022 사양에 표준화 되었기 때문에 브라우저 지원 현황을 고려해야 한다.
			throw new Error('cb error', { cause: e });
		}
	}
};

try {
	repeat(() => {
		throw new Error('Something happen in cb');
	}, 1);
} catch (e) {
	// Error.prototype에 정의된 프로퍼티는 다양하지만 대부분 비표준(non-standard) 프로퍼티다.
	console.log(e);
	console.log(e.message);
	console.log(e.name);
	console.log(e.toString()); // name + message 정보가 같이 출력된다.

	// Error.prototype.stack 프로퍼티는 비표준 프로퍼티지만, 프로덕션 환경에서 사용하지 않고 개발(development) 모드에서 유용하게 사용되는, 거의 사실상 표준인 프로퍼티(de facto property)라 한다.
	console.log(e.stack);
}
```
